### ISSUE TITLE
phpDoc for autocomplete in "__" class

### ISSUE THREAD

**Issue by iJackUA** [maciejczyzewski/bottomline#3]
Great work, the only thing is missing - phpDoc for automplete
here https://github.com/MaciejCzyzewski/bottomline/blob/master/src%2F__%2Fload.php#L28
should be added something like
```
/**
 * @method static array append(array $array, mixed $element)
 * @method static bool isArray(array $array)
...
 */
```

**Comment by Meabed** [comment]
:+1:  yes please
