### ISSUE TITLE
Propose: detailed contributing guidelines

### ISSUE THREAD

**Issue by lightbringer1991** [maciejczyzewski/bottomline#31]
So I noticed that the contribution section is very simple and there are not much instruction on how to do certain things. E.g. fork the repository and work on it before opening pull requests.

I would like to have some sort of detailed instructions so it is easier for other people to get on board.
I'd like to port more functions from lodash to bottomline in the future, since I like the idea of an utility library.

I'm happy to create a PR for that, probably in the next few days if possible.

**Comment by MonsieurV** [comment]
Yeah, good idea for a `CONTRIBUTING.md`

I think it may be kept simple, but whatever is not dead-obvious has a great place in the guidelines.

Actually you're right, there is indeed a minimal process to follow:
* add tests for the new function
* place the function where it belongs (collections, arrays, utilities etc.)
* add `README.md` doc entry for the function

Bonus:
* update the `CHANGELOG.md`
* update the benchmark (`bench.php`)?

**Comment by allejo** [comment]
Should adding the function to `__/load.php` via a `@method` also be in that process?

**Comment by MonsieurV** [comment]
Oh, yeah too!

+ incrementing [the number of functions](https://github.com/maciejczyzewski/bottomline/blob/7a273349eede3099cfae3bea8fd6d04e13a2da90/src/__/load.php#L11) if we choose to keep this file up to date

Maybe @maciejczyzewski will tell what is important (generally or not)

**Comment by maciejczyzewski** [comment]
Tests are very important // every function should be documented in README.md.
This two things are the most general/basic actions that every contr. should perform.

@MonsieurV But there are some more issues, when we change version?
- for example, from *.1.* to *.2.* if there was 3-6 changes in function API.
We should discuss this topic too...

**Comment by lightbringer1991** [comment]
I also notice that we don't have code coverage report in CI, not yet anyway.
One related thing will be assuring >90% code coverage on new pull requests, or maybe even 100%

however this is a later thing

so for now, we have:

- installation guide
- add new/fix existing functions (make sure that they are in the right place)
- write tests (edge cases are also important)
- update `README.md`
- update `__/load.php`

Not sure if I missed anything...

Regarding the versioning, I think we need a roadmap of features/functions to be added, so we can release when we reach a milestone. That way we can split it into minor version as well.

**Comment by allejo** [comment]
This isn't so much an issue with contributing directly and probably needs a separate issue but since `__/load.php` has been mentioned. Is there a more clever approach to handling docs for functions? A lot of the helpful examples are lost unless you explicitly call the namespaced function.

e.g. If you hover over `__::someFxn()` in an IDE you'll see the shortened `@method` description and not the full docs that are in each respective `__/collections/someFxn.php` file. Though, this is likely a limitation with phpdoc itself.
