### ISSUE TITLE
Support for "a.b" notation for hasKeys

### ISSUE THREAD

**Issue by MartijnZuijd** [maciejczyzewski/bottomline#38]
Lodash `has` supports dot notation to check subfields, bottomline's `hasKeys` function does not. When dealing with complex structures the dot notation prevents a lot of different hasKeys statements when checking against nested fields. 

relevant lodash doc: https://lodash.com/docs/4.17.4#has

**Comment by allejo** [comment]
`__::get()` could probably be duplicated modified to be a `__::has()`. However, you can do something like this for now. The third parameter in `__::get()` is the default value if the key is not found.

```php
$hasKey = (null === __::get($array, 'foo.bar', null));
```

**Comment by MonsieurV** [comment]
Yes, we can support that. (There's [a TODO](https://github.com/maciejczyzewski/bottomline/pull/37/commits/8c1cdc7bdd1a4dad676018cd4eb9097a2314b8f2#diff-6b0c91f65738a9e1ae741d352fa79b96R24) indeed)

Actually dot notation implementation should be factorized between `__::get()`, `__::set()`, `__::has()` (and others)

**Comment by MonsieurV** [comment]
@MartijnZuijd you know have both `__::has()` and `__::hasKeys` available for your use, with path notation.

See [doc](https://github.com/maciejczyzewski/bottomline/blob/46f29dcf874e6ff22f0e800ed1529c47d888042a/README.md#__has)

(`__::has()` recommended over `__::hasKeys`, except if you want to check a batch of keys)
