### ISSUE TITLE
Support ArrayAccess objects in __::get()

### ISSUE THREAD

**Issue by allejo** [maciejczyzewski/bottomline#40]
For `__::get()`, thoughts on adding support for objects that implement `ArrayAccess`?

**Comment by MonsieurV** [comment]
Currently what does it do? When given an object, it always try to access by property name (using object accessor)?

Maybe add [a test case](https://github.com/maciejczyzewski/bottomline/blob/master/tests/collections.php#L280) about the behavior you would expect.

**Comment by allejo** [comment]
Yea, it currently accesses the property assuming it's public, i.e. with `->`. If the object implements `ArrayAccess` it should skip down to the accessing as an array part.
