### ISSUE TITLE
functions working on collections like first should work on iterables

### ISSUE THREAD

**Issue by MartijnZuijd** [maciejczyzewski/bottomline#45]
As of now this is not possible making thinks like getting the first value of an iterator not possible.
the using the keyword iterable since version 7.1 should solve this as both primitive arrays and Iterator implementation would are considered iterable . 
https://secure.php.net/manual/en/language.types.iterable.php

**Comment by MonsieurV** [comment]
Hi @MartijnZuijd,

Could you provide examples to test and compare both cases?

**Comment by MonsieurV** [comment]
I've tried an implementation for Iterables.

See https://github.com/maciejczyzewski/bottomline/commit/a09d67a5f20361e218cb26e23884bddf98daa81f#diff-f15e9274c7d231de941ef1023a6add02R214

Should we update all our collection implementations in this way? What do you think? @allejo @maciejczyzewski @MartijnZuijd 

With `foreach` based implementations, it will work with both arrays (on PHP versions <7.1) and Iterables, although it may not be the most elegant code.

**Comment by MonsieurV** [comment]
For the performance, the `foreach` implementation of `first` is less efficient than the one using `array_slice`/`array_shift`:

```
make bench 
php tools/bench.php
Start 100000 executions
first: 0.04119sec
firstIterables: 0.07145sec

Total: 19.28531sec
Memory: 2mb
```

However I don't see other way to implement that ; and this seems reasonable that `array_slice` are more optimized than our own implementation.

**Comment by allejo** [comment]
> Should we update all our collection implementations in this way? What do you think?
> 
> With `foreach` based implementations, it will work with both arrays (on PHP versions <7.1) and Iterables, although it may not be the most elegant code.

I have no objections on moving to `foreach` loops to support iterators. However, a lot of the functions in the collection namespace make use of PHP `array_*` functions. Is what you're thinking that each function is going to have separate logic for iterators and arrays?

**Comment by MonsieurV** [comment]
Indeed, we can do that.

I see three ways forward:
1. choose _not_ to support [`Iterables`](https://secure.php.net/manual/en/language.types.iterable.php);
2. support `Iterables`, with _separate_ logic as you mention (`foreach`-based implementation for Iterables; `array_*` functions for arrays to preserve performance when we can);
3. support `Iterables` and make `foreach` the _unique_ base for all our implementations.

The `1.` seems not appropriate if we want to keep the library as universally-applicable as possible in the PHP world. `2.` is a lot more code to support and a risk for non-uniform behavior. `3.` may pose a performance issue (should be assessed on several functions to really know).

Unified implementation seems best if we can preserve - or not worsen following your POV - performance. Maybe we can start by assessing that? What do you think?

**Comment by allejo** [comment]
I'd be interested in option `3.` and see how much of a difference in performance there'd be. Sure we'd take a hit by moving away from optimized built-in functions but if the difference is negligible and the maintainability is better, I'll take that.

**Comment by MonsieurV** [comment]
Agree on your reasoning.

I've done an implementation test on another benchmark-ed function - `filter` - and here the result:

```
✗ make bench
php tools/bench.php
Start 100000 executions
filter: 0.07126sec
filterIterables: 0.10998sec
first: 0.03447sec
firstIterables: 0.06961sec
```

So seems we'll have performances worst up to two times the original; but we remains on the same performance order. That's fine for me, as anyway if you're really searching for performance (over function and practicability), you don't go for bottomline first.

**Comment by MonsieurV** [comment]
@allejo How do we proceed? Do you want to take on some of the function implementation?

From `__::assign` to `__::where`, seems there are 27 functions, including the two already implemented. Would be glad to share that.

**Comment by allejo** [comment]
That performance difference is actually much better than I was expecting! I'm satisfied with those results.

Sure! I'd be more than happy to help with the implementations. We can split them up however you'd like.

**Comment by allejo** [comment]
> Let's say you'll take from `assign` to `last`: assign, concat, concatDeep, doForEach, doForEachRight, ease, every, get, groupBy, has, hasKeys, isEmpty, last.

Sounds good to me! :+1:

I'll make a PR against the `iterable_support` branch

**Comment by allejo** [comment]
@MonsieurV as I was looking at a lot of these functions, how do you propose we handle iterators for functions that create something new? For example, we have `concat` that would return a combined array or object depending on what's given. For iterators, do you think we should build as an array and then give it over to an `ArrayIterator` or should we return the raw array?

**Comment by MonsieurV** [comment]
Giving an answer _a priori_ (without listening to other users and look at a representative set of use cases), I'll way we can return arrays for now.

My reasoning is the following: for these functions (and tell me if I'm wrong), we _exhaust_ / consume all of the data the `Iterable` has to give us to process the result; and we'll return only when we're finished. (Not sure to see the point of consuming part only of the operation on a `concat` operation; also not sure we can implement it reasonably well)
As we treat and return all the data, there is no value-added in returning it as an iterators / data flow. 

If the user need then to consume it as an Iterable, they can themself create an `ArrayIterator`

**Comment by MonsieurV** [comment]
That was my answer _a priori_, "à chaud" as frenchies say.

Looking now at the operations we provide, I try to locate which could be conceived to be used in a [yielding](https://www.php.net/manual/en/language.generators.syntax.php) mode / as a partial flux of data / as `Iterables`.

Here the functions where it may make sense:
* `chunk`: could consume and yield chunk by chunk (and the user can stop consuming without the input been exhausted
* `drop` we could imagine dropping N elements of a flux and only consuming part of the remaining data
* `filter` could totally see the point of filtering a flux of data, without loading all the data in memory and making it pass through the filter
* `get`: return first match on a flux of data
Idem for (where we think the functions are working on flux of data): `compact`, `prepend`, `doForEach`, `groupBy`, `map`, `where`

Functions where I think it doesn't make sense at all:
* `append`: we have to consume all data to append at the end
* `flatten`: seems tricky to implement with yielding and I don't see the use
* `patch`: doesn't make much sense if not applied on all the data
* `every`: have to consume all data to give a result
Idem for `randomize`, `doForEachRight`, `has`, `isEmpty`, `hasKeys`, `last`, `merge`, `reduce`, `set`, `:pick`

I've not listed all the functions. However looking at the list I observe:
1. we can see a point of having several functions working on flux of data (yielding data), where it can be used on big or live data flux with memory or liveness constraints
2. implementing that seems a big reshape or work on the API, implementation and documentation: this means some of the function yielding (no point in consuming all the data and returning an `ArrayIterator` on it: can't be used to limit memory usage on big datasets or work on live streams, for that we need generators/yielding) and other not returning arrays, so we'll have to document it and educate users

This is a lot more work on the implementation, and may be too ambitious to begin with. However there are interesting use cases (filtering on data stream; or mapping a big CSV input to another output stream, as a database or other file, without consuming too much memory) and we could discuss their implementation and API _in a second step_ (ideally with feedback from users of this first API upgrade; and with some preliminary / exploratory research and tests done).

That's my more constructed opinion :)
