### ISSUE TITLE
Automate full documentation

### ISSUE THREAD

**Issue by allejo** [maciejczyzewski/bottomline#50]
Since #44 was merged, the magic method loader class has its documentation automatically generated for up to date PHPDocs. This allows us to maintain the documentation right next to the functions themselves.

I'd like to propose hosting the documentation as a Jekyll website. In the current `phpDocGen.php` script, we have all the documentation in memory. We can take advantage of that by generating a JSON file and dumping that file inside of a new `docs/` folder (GitHub allows for a Jekyll site to live in `docs/`). Then we just build a Jekyll site to read that JSON file and make it pretty.

This will allow us to run `phpDocGen.php` and it will automagically generate our new loader for distribution via Packagist **and** it'll generate a new JSON file for our Jekyll site to parse and build into an always up-to-date website.

Thoughts?

/cc @MonsieurV @maciejczyzewski

**Comment by MonsieurV** [comment]
Hi @allejo,

Totally favorable for having a static website generated for the doc - still more if you do most of the work! :sweat_smile: :+1: 

Would be super nice to have our documentation content with the function listing searchable: our README is getting big.

However I think we'll need an action from @maciejczyzewski for that: to enable the GitHub Pages feature on the project. Maybe you can mail him to get his attention ;) :wave:

**Comment by allejo** [comment]
> Totally favorable for having a static website generated for the doc - still more if you do most of the work! 😅 👍

I'm fine with that! I have the process in mind, so I'll work on that once I finish up my work on #48.

> However I think we'll need an action from @maciejczyzewski for that: to enable the GitHub Pages feature on the project. Maybe you can mail him to get his attention ;) 👋

I'll shoot him an email :+1:

**Comment by maciejczyzewski** [comment]
Okay, so a moment ago I have created `docs/` path & configured page deploy env. (permissions for @allejo). For now, I just put 'hello world' to test if it's working properly ;-)

**Comment by allejo** [comment]
Thanks @maciejczyzewski!!
