### ISSUE TITLE
Configure Packagist to auto update from GitHub

### ISSUE THREAD

**Issue by allejo** [maciejczyzewski/bottomline#53]
Can we please have packagist configures to auto update?

**Comment by allejo** [comment]
Gonna nudge you on this one @maciejczyzewski. I want to tag an alpha/RC for a 0.2.0 soon.

**Comment by maciejczyzewski** [comment]
It should work: https://packagist.org/packages/maciejczyzewski/bottomline#dev-master

<img width="245" alt="Screen Shot 2020-03-23 at 22 11 33" src="https://user-images.githubusercontent.com/1976088/77363581-4c6ac400-6d53-11ea-8ed2-2b54fb0e5ee4.png">

**Comment by allejo** [comment]
Yup! Looks like we're all set, thanks so much! :smile:

![image](https://user-images.githubusercontent.com/1246453/77364287-6e435700-6d11-11ea-96ea-b4933d251c17.png)
